// src/pages/ResetPassword.jsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { Lock, AlertCircle, CheckCircle, ArrowLeft, RefreshCw } from 'lucide-react';

export default function ResetPassword() {
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);
  const [loading, setLoading] = useState(false);
  const [sessionChecking, setSessionChecking] = useState(true);
  const [hasRecoverySession, setHasRecoverySession] = useState(false);

  const navigate = useNavigate();

  useEffect(() => {
    let mounted = true;

    // 1. Check existing session on mount
    const checkSession = async () => {
      try {
        const { data: { session } } = await supabase.auth.getSession();
        
        // Check hash parameters for recovery token if session is not yet loaded
        const hash = window.location.hash || '';
        const search = window.location.search || '';
        const isRecoveryUrl = hash.includes('type=recovery') || hash.includes('access_token') || search.includes('code=');

        if (session || isRecoveryUrl) {
          if (mounted) setHasRecoverySession(true);
        } else {
          if (mounted) setHasRecoverySession(false);
        }
      } catch (err) {
        console.warn('Error checking recovery session:', err.message);
        if (mounted) setHasRecoverySession(false);
      } finally {
        if (mounted) setSessionChecking(false);
      }
    };

    checkSession();

    // 2. Listen to PASSWORD_RECOVERY auth state event
    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      if (event === 'PASSWORD_RECOVERY' || (session && event === 'SIGNED_IN')) {
        if (mounted) {
          setHasRecoverySession(true);
          setSessionChecking(false);
        }
      }
    });

    return () => {
      mounted = false;
      subscription?.unsubscribe();
    };
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    if (!password || !confirmPassword) {
      setError('Please fill in both password fields.');
      return;
    }

    if (password !== confirmPassword) {
      setError('Passwords do not match.');
      return;
    }

    if (password.length < 6) {
      setError('Password must be at least 6 characters long.');
      return;
    }

    setLoading(true);

    try {
      // Execute standard Supabase Auth password update
      const { error } = await supabase.auth.updateUser({
        password: password
      });

      if (error) throw error;

      // Sign out to ensure user logs in with their new credentials
      await supabase.auth.signOut();
      setSuccess(true);
    } catch (err) {
      setError(err.message || 'Failed to update user password. Your recovery session may have expired.');
    } finally {
      setLoading(false);
    }
  };

  if (sessionChecking) {
    return (
      <div className="auth-page-container container" style={{ padding: '80px 20px', maxWidth: '480px' }}>
        <div className="auth-card" style={{ padding: '40px', border: '1px solid var(--color-border)', borderRadius: 'var(--border-radius-md)', background: 'var(--color-white)', textAlign: 'center' }}>
          <div className="loading-spinner" style={{ border: '3px solid var(--color-primary-light)', borderTop: '3px solid var(--color-rose)', borderRadius: '50%', width: '36px', height: '36px', animation: 'spin 1s linear infinite', margin: '0 auto 15px' }}></div>
          <p style={{ color: 'var(--color-neutral-muted)', fontSize: '0.85rem' }}>Verifying password recovery session...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="auth-page-container container" style={{ padding: '80px 20px', maxWidth: '480px' }}>
      <div className="auth-card animate-slide-up" style={{ padding: '40px', border: '1px solid var(--color-border)', borderRadius: 'var(--border-radius-md)', background: 'var(--color-white)', boxShadow: '0 10px 30px rgba(0,0,0,0.03)' }}>
        <div style={{ textAlign: 'center', marginBottom: '25px' }}>
          <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.8rem', color: 'var(--color-neutral-dark)', marginBottom: '8px' }}>Set New Password</h2>
          <p style={{ fontSize: '0.85rem', color: 'var(--color-neutral-muted)' }}>Enter your new password below</p>
        </div>

        {error && (
          <div className="alert alert-error" style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '12px', background: '#FFF5F5', color: '#C94B4B', borderRadius: '4px', fontSize: '0.85rem', marginBottom: '20px', border: '1px solid #FFD8D8' }}>
            <AlertCircle size={16} style={{ flexShrink: 0 }} />
            <span>{error}</span>
          </div>
        )}

        {success ? (
          <div style={{ textAlign: 'center', padding: '10px 0' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '15px', background: '#EAF8EB', color: '#4E8752', borderRadius: '4px', fontSize: '0.9rem', marginBottom: '20px', border: '1px solid #C1EFC4', textAlign: 'left' }}>
              <CheckCircle size={18} style={{ flexShrink: 0 }} />
              <span>Your password has been updated successfully! You can now log in with your new password.</span>
            </div>
            <button
              onClick={() => navigate('/login')}
              className="btn btn-primary"
              style={{ width: '100%', height: '44px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '1px' }}
            >
              Return to Login
            </button>
          </div>
        ) : !hasRecoverySession ? (
          <div style={{ textAlign: 'center', padding: '10px 0' }}>
            <div className="alert alert-error" style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '15px', background: '#FFF5F5', color: '#C94B4B', borderRadius: '4px', fontSize: '0.85rem', marginBottom: '20px', border: '1px solid #FFD8D8', textAlign: 'left' }}>
              <AlertCircle size={18} style={{ flexShrink: 0 }} />
              <span>Invalid or expired password reset link. Please request a new recovery link.</span>
            </div>
            <Link to="/forgot-password" className="btn btn-primary" style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: '8px', width: '100%', height: '44px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '1px' }}>
              <RefreshCw size={14} /> Request New Reset Link
            </Link>
          </div>
        ) : (
          <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '18px' }}>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', textAlign: 'left' }}>
              <label style={{ fontSize: '0.75rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.5px', color: 'var(--color-neutral-dark)' }}>New Password</label>
              <div style={{ position: 'relative' }}>
                <input
                  type="password"
                  required
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="Minimum 6 characters"
                  style={{ width: '100%', height: '42px', padding: '0 12px 0 35px', border: '1px solid var(--color-border)', borderRadius: '4px', fontSize: '0.9rem' }}
                />
                <Lock size={16} style={{ position: 'absolute', left: '12px', top: '13px', color: 'var(--color-rose)' }} />
              </div>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', textAlign: 'left' }}>
              <label style={{ fontSize: '0.75rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.5px', color: 'var(--color-neutral-dark)' }}>Confirm New Password</label>
              <div style={{ position: 'relative' }}>
                <input
                  type="password"
                  required
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  placeholder="Re-enter new password"
                  style={{ width: '100%', height: '42px', padding: '0 12px 0 35px', border: '1px solid var(--color-border)', borderRadius: '4px', fontSize: '0.9rem' }}
                />
                <Lock size={16} style={{ position: 'absolute', left: '12px', top: '13px', color: 'var(--color-rose)' }} />
              </div>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="btn btn-primary"
              style={{ width: '100%', height: '44px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '1px', marginTop: '10px' }}
            >
              {loading ? 'Updating Password...' : 'Save New Password'}
            </button>

            <Link to="/login" style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: '6px', color: 'var(--color-neutral-muted)', fontSize: '0.85rem', fontWeight: 600, marginTop: '10px' }}>
              <ArrowLeft size={14} /> Cancel & Return to Login
            </Link>
          </form>
        )}
      </div>
    </div>
  );
}

// src/app/pages/auth/reset-password.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../core/services/auth.service';
import { SupabaseService } from '../../core/services/supabase.service';

@Component({
  selector: 'app-reset-password',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  template: `
    <div class="auth-page">
      <div class="auth-card">
        <div class="auth-header">
          <div class="logo-circle-wrapper">
            <img src="https://i.ibb.co/KjcmQcmy/Whats-App-Image-2026-08-13-at-10-59-05-AM.jpg" alt="Petals Ethnic Logo" class="auth-logo" />
          </div>
          <h1 class="auth-title">Update Password</h1>
          <p class="auth-subtitle">Enter your new password to update your Petals Ethnic account.</p>
        </div>

        <div *ngIf="successMessage" class="auth-alert success">
          {{ successMessage }}
        </div>

        <div *ngIf="errorMessage" class="auth-alert error">
          {{ errorMessage }}
        </div>

        <form (ngSubmit)="onSubmit()" class="auth-form" *ngIf="!successMessage && !isLinkExpired">
          <div class="form-group">
            <label class="form-label" for="password">New Password</label>
            <input 
              type="password" 
              id="password" 
              [(ngModel)]="newPassword" 
              name="password" 
              required 
              placeholder="At least 6 characters" 
              class="form-control"
            />
          </div>

          <div class="form-group">
            <label class="form-label" for="confirmPassword">Confirm New Password</label>
            <input 
              type="password" 
              id="confirmPassword" 
              [(ngModel)]="confirmPassword" 
              name="confirmPassword" 
              required 
              placeholder="Confirm new password" 
              class="form-control"
            />
          </div>

          <button type="submit" [disabled]="isLoading" class="btn-primary auth-submit-btn">
            {{ isLoading ? 'Updating Password...' : 'Update Password' }}
          </button>
        </form>

        <div class="auth-footer" *ngIf="successMessage">
          <a routerLink="/login" class="btn-primary">Proceed to Sign In →</a>
        </div>

        <div class="auth-footer" *ngIf="isLinkExpired">
          <a routerLink="/forgot-password" class="btn-primary">Request New Reset Link →</a>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .auth-page {
      padding: 60px 24px;
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 70vh;
      background-color: var(--color-bg-alt);
    }
    .auth-card {
      background: #FFFFFF;
      width: 100%;
      max-width: 440px;
      padding: 40px;
      border-radius: var(--radius-lg);
      border: 1px solid var(--color-border-light);
      box-shadow: var(--shadow-md);
    }
    .auth-header {
      text-align: center;
      margin-bottom: 28px;
    }
    .logo-circle-wrapper {
      width: 64px;
      height: 64px;
      border-radius: 50%;
      overflow: hidden;
      margin: 0 auto 16px auto;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
      background: #FFFFFF;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .auth-logo {
      width: 100%;
      height: 100%;
      object-fit: cover;
    }
    .auth-title {
      font-size: 28px;
      margin-bottom: 8px;
    }
    .auth-subtitle {
      font-size: 13px;
      color: var(--color-muted);
    }
    .auth-alert {
      padding: 12px;
      border-radius: var(--radius-sm);
      font-size: 13px;
      margin-bottom: 20px;
    }
    .auth-alert.success {
      background-color: #E8F5E9;
      color: #2E7D32;
      border: 1px solid #C8E6C9;
    }
    .auth-alert.error {
      background-color: #FFEBEE;
      color: #C62828;
      border: 1px solid #FFCDD2;
    }
    .auth-submit-btn {
      width: 100%;
      padding: 14px;
      margin-top: 10px;
    }
    .auth-footer {
      text-align: center;
      margin-top: 24px;
    }
  `]
})
export class ResetPasswordComponent implements OnInit, OnDestroy {
  newPassword = '';
  confirmPassword = '';
  isLoading = false;
  isLinkExpired = false;
  successMessage = '';
  errorMessage = '';
  private authSubscription: any;

  constructor(
    private authService: AuthService,
    private supabaseService: SupabaseService,
    private router: Router
  ) {}

  async ngOnInit() {
    // Check current auth session
    const { data: { session } } = await this.supabaseService.supabase.auth.getSession();

    const { data: listener } = this.supabaseService.supabase.auth.onAuthStateChange((event, session) => {
      if (event === 'PASSWORD_RECOVERY' || session) {
        this.isLinkExpired = false;
        this.errorMessage = '';
      }
    });
    this.authSubscription = listener.subscription;

    if (!session && !window.location.hash.includes('access_token') && !window.location.href.includes('type=recovery')) {
      this.isLinkExpired = true;
      this.errorMessage = 'This password reset link is invalid or has expired. Please request a new link.';
    }
  }

  ngOnDestroy() {
    if (this.authSubscription) {
      this.authSubscription.unsubscribe();
    }
  }

  async onSubmit() {
    if (!this.newPassword || !this.confirmPassword) {
      this.errorMessage = 'Please complete both password fields.';
      return;
    }

    if (this.newPassword.length < 6) {
      this.errorMessage = 'Password must be at least 6 characters.';
      return;
    }

    if (this.newPassword !== this.confirmPassword) {
      this.errorMessage = 'Passwords do not match.';
      return;
    }

    this.isLoading = true;
    this.errorMessage = '';
    this.successMessage = '';

    try {
      await this.authService.updatePassword(this.newPassword);
      this.successMessage = 'Your password has been successfully updated! You can now log in with your new password.';
    } catch (err: any) {
      console.error('Reset password error:', err);
      const msg = (err?.message || '').toLowerCase();
      if (msg.includes('jwt expired') || msg.includes('token expired') || msg.includes('session expired') || msg.includes('auth event')) {
        this.isLinkExpired = true;
        this.errorMessage = 'Your password reset link has expired. Please request a new link.';
      } else {
        this.errorMessage = err.message || 'Error updating password. Please try again.';
      }
    } finally {
      this.isLoading = false;
    }
  }
}
