// src/app/pages/contact/contact.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="contact-page">
      <div class="contact-hero">
        <div class="container text-center">
          <span class="section-subtitle">GET IN TOUCH</span>
          <h1 class="contact-title">Contact Petals Ethnic</h1>
          <p class="contact-sub">We are here to assist you with sizing, orders, and boutique inquiries.</p>
        </div>
      </div>

      <div class="container section">
        <div class="contact-grid">
          <!-- Info Column -->
          <div class="contact-info-card">
            <h2>Reach Out to Us</h2>
            <p>Have questions about a fabric or custom sizing? Connect with us through any of the channels below.</p>

            <div class="info-list">
              <div class="info-item">
                <span class="info-icon">📧</span>
                <div>
                  <strong>Email Us:</strong>
                  <a href="mailto:petalsethnic@gmail.com">petalsethnic@gmail.com</a>
                </div>
              </div>

              <div class="info-item">
                <span class="info-icon">💬</span>
                <div>
                  <strong>WhatsApp Helpline:</strong>
                  <a href="https://wa.me/918113899319" target="_blank">+91 81138 99319</a>
                </div>
              </div>

              <div class="info-item">
                <span class="info-icon">📸</span>
                <div>
                  <strong>Instagram:</strong>
                  <a href="https://www.instagram.com/petalsethnic" target="_blank">&#64;petalsethnic</a>
                </div>
              </div>

              <div class="info-item">
                <span class="info-icon">👍</span>
                <div>
                  <strong>Facebook Page:</strong>
                  <a href="https://www.facebook.com/share/1CZHBSGW22/" target="_blank">Petals Ethnic Official</a>
                </div>
              </div>
            </div>

            <div class="wa-box">
              <h3>Fastest Response on WhatsApp</h3>
              <p>Send us a text for immediate assistance on orders & styling.</p>
              <a href="https://wa.me/918113899319?text=Hello%20Petals%20Ethnic" target="_blank" class="btn-wa">
                Chat on WhatsApp Now
              </a>
            </div>
          </div>

          <!-- Form Column -->
          <div class="contact-form-card">
            <h2>Send Us a Message</h2>
            <div *ngIf="sentSuccess" class="alert success">
              ✅ Thank you! Your message has been received. We will contact you shortly.
            </div>

            <form (ngSubmit)="sendMessage()" class="contact-form" *ngIf="!sentSuccess">
              <div class="form-group">
                <label class="form-label">Your Name</label>
                <input type="text" [(ngModel)]="name" name="name" required class="form-control" placeholder="Priya" />
              </div>

              <div class="form-group">
                <label class="form-label">Email Address</label>
                <input type="email" [(ngModel)]="email" name="email" required class="form-control" placeholder="you@example.com" />
              </div>

              <div class="form-group">
                <label class="form-label">Phone Number</label>
                <input type="tel" [(ngModel)]="phone" name="phone" class="form-control" placeholder="+91 98765 43210" />
              </div>

              <div class="form-group">
                <label class="form-label">Message / Outfit Inquiry</label>
                <textarea [(ngModel)]="message" name="message" required rows="4" class="form-control" placeholder="Tell us what you're looking for..."></textarea>
              </div>

              <button type="submit" class="btn-primary full-width">Send Message</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .contact-hero {
      background-color: var(--color-bg-alt);
      padding: 60px 0;
      border-bottom: 1px solid var(--color-border-light);
    }
    .text-center { text-align: center; }
    .contact-title { font-size: 42px; margin-bottom: 8px; }
    .contact-sub { font-size: 16px; color: var(--color-muted); }
    .section { padding: 80px 0; }
    .contact-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 60px;
    }
    @media (max-width: 992px) {
      .contact-grid { grid-template-columns: 1fr; gap: 32px; }
    }
    .contact-info-card, .contact-form-card {
      background: #FFFFFF;
      border: 1px solid var(--color-border-light);
      border-radius: var(--radius-lg);
      padding: 40px;
    }
    .info-list {
      display: flex;
      flex-direction: column;
      gap: 20px;
      margin: 28px 0;
    }
    .info-item {
      display: flex;
      gap: 16px;
      align-items: center;
    }
    .info-icon { font-size: 24px; }
    .info-item a { color: #C05676; font-weight: 600; }
    .wa-box {
      background: var(--color-pink-light);
      border: 1px solid var(--color-pink);
      padding: 24px;
      border-radius: var(--radius-md);
      margin-top: 32px;
      text-align: center;
    }
    .wa-box h3 { margin-bottom: 8px; }
    .wa-box p { font-size: 13px; color: var(--color-muted); margin-bottom: 16px; }
    .btn-wa {
      display: inline-block;
      background-color: #25D366;
      color: #FFFFFF;
      padding: 12px 24px;
      border-radius: var(--radius-full);
      font-weight: 600;
    }
    .full-width { width: 100%; padding: 14px; }
    .alert.success {
      background-color: #E8F5E9;
      color: #2E7D32;
      padding: 16px;
      border-radius: 4px;
      font-size: 14px;
    }
  `]
})
export class ContactComponent {
  name = '';
  email = '';
  phone = '';
  message = '';
  sentSuccess = false;

  sendMessage() {
    if (this.name && this.email && this.message) {
      this.sentSuccess = true;
    }
  }
}

// src/pages/Contact.jsx
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { Mail, Phone, Send, MessageSquare, Check } from 'lucide-react';

// Custom Instagram SVG for stability
const InstagramIcon = ({ size = 20, className = "" }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
    <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
    <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
    <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
  </svg>
);

export default function Contact() {
  const [formSubmitted, setFormSubmitted] = useState(false);
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    subject: '',
    message: ''
  });

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleFormSubmit = (e) => {
    e.preventDefault();
    if (formData.name && formData.email) {
      setFormSubmitted(true);
      setFormData({ name: '', email: '', subject: '', message: '' });
    }
  };

  const whatsappUrl = "https://wa.me/918113899319?text=Hello%20Petals%20Ethnic!%20I'd%20like%20to%20inquire%20about%20your%20collections.";

  return (
    <div className="contact-page-wrapper">
      {/* Page Header */}
      <div className="page-header">
        <div className="container">
          <h1>Contact Us</h1>
          <div className="breadcrumbs">
            <Link to="/">Home</Link> <span>/</span> <span className="active-breadcrumb">Contact</span>
          </div>
        </div>
      </div>

      {/* Main Grid */}
      <div className="container contact-grid" style={{ paddingBottom: '80px', display: 'grid', gridTemplateColumns: '1fr 1.25fr', gap: '50px' }}>
        {/* Left: Contact Info Channels */}
        <div className="contact-info-column animate-slide-up">
          <span className="contact-pre" style={{ textTransform: 'uppercase', letterSpacing: '2px', fontSize: '0.85rem', color: 'var(--color-gold)', display: 'block', marginBottom: '10px' }}>
            Get in touch
          </span>
          <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '2.5rem', marginBottom: '20px' }}>We'd love to help you</h2>
          <p style={{ color: 'var(--color-neutral-muted)', marginBottom: '40px' }}>
            Have questions about custom sizing, shipping times, or fabric details? Let us know what you are looking for, and we'll be happy to help you find the best outfit!
          </p>

          {/* Contact Details List */}
          <div className="contact-channels-list" style={{ display: 'flex', flexDirection: 'column', gap: '30px' }}>
            {/* WhatsApp CTA */}
            <div className="contact-channel-item" style={{ display: 'flex', gap: '20px' }}>
              <div className="contact-icon-box" style={{ width: '50px', height: '50px', borderRadius: '50%', background: 'var(--color-primary-light)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--color-primary-dark)' }}>
                <MessageSquare size={20} />
              </div>
              <div>
                <h4 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.1rem', marginBottom: '5px' }}>WhatsApp & Chat</h4>
                <p style={{ color: 'var(--color-neutral-muted)', fontSize: '0.95rem', marginBottom: '8px' }}>Chat with our stylists directly for instant outfit assistance.</p>
                <a 
                  href={whatsappUrl} 
                  target="_blank" 
                  rel="noopener noreferrer" 
                  className="btn btn-secondary"
                  style={{ padding: '0.5rem 1.25rem', fontSize: '0.8rem', textTransform: 'none', letterSpacing: '0.5px' }}
                >
                  Message +91 81138 99319
                </a>
              </div>
            </div>

            {/* Email Channel */}
            <div className="contact-channel-item" style={{ display: 'flex', gap: '20px' }}>
              <div className="contact-icon-box" style={{ width: '50px', height: '50px', borderRadius: '50%', background: 'var(--color-primary-light)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--color-primary-dark)' }}>
                <Mail size={20} />
              </div>
              <div>
                <h4 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.1rem', marginBottom: '5px' }}>Email Support</h4>
                <p style={{ color: 'var(--color-neutral-muted)', fontSize: '0.95rem', marginBottom: '5px' }}>Drop us a line and we'll reply within 24 hours.</p>
                <a href="mailto:petalsethnic@gmail.com" style={{ fontWeight: '500', color: 'var(--color-neutral-dark)', borderBottom: '1px solid var(--color-neutral-dark)' }}>
                  petalsethnic@gmail.com
                </a>
              </div>
            </div>

            {/* Social Medias */}
            <div className="contact-channel-item" style={{ display: 'flex', gap: '20px' }}>
              <div className="contact-icon-box" style={{ width: '50px', height: '50px', borderRadius: '50%', background: 'var(--color-primary-light)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--color-primary-dark)' }}>
                <InstagramIcon size={20} />
              </div>
              <div>
                <h4 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.1rem', marginBottom: '5px' }}>Follow Our Journey</h4>
                <p style={{ color: 'var(--color-neutral-muted)', fontSize: '0.95rem', marginBottom: '8px' }}>Follow us on Facebook and Instagram for styling reels and giveaways.</p>
                <div style={{ display: 'flex', gap: '15px' }}>
                  <a href="https://www.instagram.com/petalsethnic" target="_blank" rel="noopener noreferrer" className="btn-text" style={{ fontSize: '0.9rem', textTransform: 'none' }}>
                    Instagram
                  </a>
                  <a href="https://www.facebook.com/share/1CZHBSGW22/" target="_blank" rel="noopener noreferrer" className="btn-text" style={{ fontSize: '0.9rem', textTransform: 'none' }}>
                    Facebook
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Right: Contact Form Panel */}
        <div className="contact-form-column animate-slide-up" style={{ animationDelay: '0.1s' }}>
          <div style={{ background: '#fff', padding: '40px', borderRadius: 'var(--border-radius-lg)', border: '1px solid var(--color-border)', boxShadow: '0 8px 30px var(--color-card-shadow)' }}>
            {formSubmitted ? (
              <div className="form-success text-center" style={{ padding: '30px 10px' }}>
                <div className="success-icon-circle" style={{ width: '60px', height: '60px', borderRadius: '50%', background: '#E8F5E9', color: '#2E7D32', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 20px' }}>
                  <Check size={28} />
                </div>
                <h3>Message Sent Successfully!</h3>
                <p style={{ color: 'var(--color-neutral-muted)', marginTop: '10px' }}>
                  Thank you for writing to Petals Ethnic. Our customer assistant will review your query and get in touch with you shortly.
                </p>
                <button onClick={() => setFormSubmitted(false)} className="btn btn-outline" style={{ marginTop: '20px' }}>
                  Send Another Message
                </button>
              </div>
            ) : (
              <form onSubmit={handleFormSubmit}>
                <h3 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.6rem', marginBottom: '20px' }}>Send Us A Message</h3>
                
                <div className="form-group">
                  <label className="form-label">Full Name</label>
                  <input
                    type="text"
                    name="name"
                    value={formData.name}
                    onChange={handleInputChange}
                    className="form-input"
                    placeholder="Enter your name"
                    required
                  />
                </div>

                <div className="form-group">
                  <label className="form-label">Email Address</label>
                  <input
                    type="email"
                    name="email"
                    value={formData.email}
                    onChange={handleInputChange}
                    className="form-input"
                    placeholder="Enter your email"
                    required
                  />
                </div>

                <div className="form-group">
                  <label className="form-label">Subject</label>
                  <input
                    type="text"
                    name="subject"
                    value={formData.subject}
                    onChange={handleInputChange}
                    className="form-input"
                    placeholder="e.g. Sizing query, shipping help"
                  />
                </div>

                <div className="form-group">
                  <label className="form-label">Message / Inquiry</label>
                  <textarea
                    name="message"
                    rows="5"
                    value={formData.message}
                    onChange={handleInputChange}
                    className="form-input"
                    style={{ resize: 'vertical', minHeight: '120px' }}
                    placeholder="Describe what you are looking for..."
                    required
                  ></textarea>
                </div>

                <button type="submit" className="btn btn-primary" style={{ width: '100%', marginTop: '10px' }}>
                  Submit Inquiry <Send size={16} />
                </button>
              </form>
            )}
          </div>
        </div>
      </div>
      
      {/* Responsive adjustments (handled in index.css, adding fallbacks for direct columns) */}
      <style>{`
        @media (max-width: 900px) {
          .contact-grid {
            grid-template-columns: 1fr !important;
            gap: 40px !important;
          }
        }
      `}</style>
    </div>
  );
}
